# Form implementation generated from reading ui file '/home/javi/Escritorio/escuela/practicaRepo/repo3ero/chat/cliente/interfaz/canal.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(344, 125)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.ip = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.ip.setObjectName("ip")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.ip)
        self.Aceptar = QtWidgets.QPushButton(parent=Form)
        self.Aceptar.setGeometry(QtCore.QRect(130, 80, 80, 23))
        self.Aceptar.setObjectName("Aceptar")
        self.Cancelar = QtWidgets.QPushButton(parent=Form)
        self.Cancelar.setGeometry(QtCore.QRect(220, 80, 80, 23))
        self.Cancelar.setObjectName("Cancelar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Canal"))
        self.label.setText(_translate("Form", "IP:"))
        self.Aceptar.setText(_translate("Form", "Aceptar"))
        self.Cancelar.setText(_translate("Form", "Canclar"))
