# Form implementation generated from reading ui file '/home/javi/Escritorio/escuela/practicaRepo/repo3ero/chat/cliente/interfaz/perfil.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(529, 152)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 501, 83))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.nombrePefil = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.nombrePefil.setObjectName("nombrePefil")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nombrePefil)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.descripcionPerfil = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.descripcionPerfil.setObjectName("descripcionPerfil")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.descripcionPerfil)
        self.colores = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.colores.setObjectName("colores")
        self.colores.addItem("")
        self.colores.addItem("")
        self.colores.addItem("")
        self.colores.addItem("")
        self.colores.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.colores)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.Aceptar = QtWidgets.QPushButton(parent=Form)
        self.Aceptar.setGeometry(QtCore.QRect(320, 120, 80, 23))
        self.Aceptar.setObjectName("Aceptar")
        self.Cancelar = QtWidgets.QPushButton(parent=Form)
        self.Cancelar.setGeometry(QtCore.QRect(410, 120, 80, 23))
        self.Cancelar.setObjectName("Cancelar")
        self.colormuestra = QtWidgets.QLabel(parent=Form)
        self.colormuestra.setGeometry(QtCore.QRect(100, 110, 41, 31))
        self.colormuestra.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"border-style:solid;\n"
"border-width:1px\n"
"")
        self.colormuestra.setText("")
        self.colormuestra.setObjectName("colormuestra")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Perfil"))
        self.label.setText(_translate("Form", "Nombre:"))
        self.label_2.setText(_translate("Form", "Descripcion:"))
        self.colores.setItemText(0, _translate("Form", "NEGRO"))
        self.colores.setItemText(1, _translate("Form", "ROJO"))
        self.colores.setItemText(2, _translate("Form", "AZUL"))
        self.colores.setItemText(3, _translate("Form", "ROSA"))
        self.colores.setItemText(4, _translate("Form", "VERDE"))
        self.label_3.setText(_translate("Form", "Color:"))
        self.Aceptar.setText(_translate("Form", "Aceptar"))
        self.Cancelar.setText(_translate("Form", "Cancelar"))
